version: '3.4'

networks:
    dev:
        driver: bridge

services:
  db:
      build:
        context: ../Database
        dockerfile: Dockerfile
      container_name: eventsDatabase
      restart: always
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=events
      ports:
          - "5433:5432"
      networks:
          - dev
      volumes:
          - app_data:/var/lib/postgresql/data
    
volumes:
    app_data:
